version: '3.5'
services:

  opal:
    container_name: datashield_opal
    restart: unless-stopped
    image: docker.miracum.org/datashield_miracum/ds_opal:v0.12.1
    ports:
      - "443:8443"
    networks:
      - opal_net
    environment:
      - OPAL_ADMINISTRATOR_PASSWORD=${OPAL_ADMIN_PASS}
      - MONGODBHOST=${OPAL_MONGODB_HOST}
      - INITTESTDATA=true
      - DS_VERSION=${DS_VERSION:-6.2.2}
      - DS_PRIVACY_LEVEL=$DS_PRIVACY_LEVEL
      - ROCK_HOSTS=rock1:8085,rock2:8085
    volumes:
      - ${QP_DATA_DIR}/opal:/srv
      - /etc/dsqp/auth:/auth
      - /etc/dsqp/miracum_users:/miracum_users

  rock1:
    restart: unless-stopped
    image: datashield/rock-base:6.2
    environment:
      - ROCK_ID=default-1
      - ROCK_CLUSTER=default
    networks:
      - opal_net

  rock2:
    image: datashield/rock-base:6.2
    restart: unless-stopped
    environment:
      - ROCK_ID=default-2
      - ROCK_CLUSTER=default
    networks:
      - opal_net


  mongo:
    container_name: datashield_mongo
    restart: unless-stopped
    image: mongo:4
    volumes:
      - ${QP_DATA_DIR}/mongo_data:/data/db
    networks:
      - opal_net

  poll_server:
    container_name: poll_server
    restart: unless-stopped
    image: docker.miracum.org/datashield_miracum/ds_poll:v0.9.1
    environment:
      - POLL_QUEUE_SERVER=${POLL_QUEUE_SERVER}
      - POLL_OPAL_SERVER=${POLL_OPAL_SERVER}
      - POLL_THREADS=${POLL_THREADS}
      - CHECK_SERVER_CERT=${CHECK_SERVER_CERT}
      - LOG_LEVEL=${LOG_LEVEL}
    entrypoint: bash -c "tail -f /dev/null"
    networks:
      - opal_net
    volumes:
      - ${QP_DATA_DIR}/poll_logging:/home/dspoll/ds_poll/logging
      - /etc/dsqp/auth:/auth

networks:
  opal_net:
    name: ds_opal_opal_net
