name: ci

on:
  push:
    branches:
      - 'master'
    tags: [ 'v*.*.*' ]

jobs:
    build_ds_opal:
      uses: ./.github/workflows/build.yaml
      with:
        package: ds_opal
        workdir: ds_opal
      secrets:
        token: ${{ secrets.GITHUB_TOKEN }}

    build_ds_poll:
      uses: ./.github/workflows/build.yaml
      with:
        package: ds_poll
        workdir: ds_poll
      secrets:
          token: ${{ secrets.GITHUB_TOKEN }}

    build_ds_queue:
      uses: ./.github/workflows/build.yaml
      with:
        package: ds_queue
        workdir: ds_queue
      secrets:
          token: ${{ secrets.GITHUB_TOKEN }}

    build_ds_queue_nginx:
      uses: ./.github/workflows/build.yaml
      with:
        package: ds_queue_nginx
        workdir: ds_queue
        dockerfile: Dockerfile.nginx.queue
      secrets:
          token: ${{ secrets.GITHUB_TOKEN }}
    build_simple_client:
      uses: ./.github/workflows/build.yaml
      with:
        package: ds_simple_client
        workdir: ds_simple_client
      secrets:
          token: ${{ secrets.GITHUB_TOKEN }}
